baseurl = "http://www.richardsumilang.com/"
languageCode = "en-us"
title = "Top Secret Labs - RichardSumilang.com"
theme = "hugo-theme-richardsumilang-dark"
SectionPagesMenu = "main"

[permalinks]
  wordpress = "/blog/:year/:month/:day/:title/"

[author]
  name = "Richard Sumilang"
  homepage = "http://www.richardsumilang.com"

[indexes]
  category = "categories"
  tag = "tags"

[Params]
  AuthorName = "Richard"
  Bitbucket = "rsumilang"
  Disqus = "richardsumilang"
  Facebook = "pages/Richard-Sumilang/1671943293041280"
  GitHub = "rsumilang"
  GooglePlus = "103897788753346013902"
  GoogleAnalytics = "UA-38936074-1"
  Instagram = "RichardSumilang"
  Linkedin = "rsumilang"
  NewsletterUrl = "http://eepurl.com/bwckhL"
  Pinterest = "rsumilang"
  Twitter = "rsumilang"
  YouTube = "UCHM2jhFZ2LkwUb_GukcMXFA"
  Email = "me@richardsumilang.com"
  Logo = "images/header-logo.png"
